name: Publish translocate

on:
  workflow_dispatch:

jobs:
  publish-translocate:
    # custom runner preinstalled with rust stable
    runs-on: ubuntu-rust-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: cargo test -- --test-threads 1

      - name: Publish cargo package
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo login $CARGO_REGISTRY_TOKEN
          cargo publish