name: Test translocate

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  test-translocate:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - 1.72.0

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy

    - name: Install dependencies
      run: |
        apt-get update
        apt-get -y install gcc-mingw-w64-x86-64 gcc-mingw-w64-i686
        rustup target add i686-pc-windows-gnu
        rustup target add x86_64-pc-windows-gnu
        rustup target add x86_64-unknown-linux-gnu
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin

    - name: Run tests and lints
      run: |
        cargo clippy
        cargo fmt --all --check
        cargo test generators -- --test-threads 1
